# Generated by Django 3.1.4 on 2021-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmindapi', '0003_auto_20210103_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
