# Generated by Django 3.1.4 on 2021-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmindapi', '0004_activity_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
